### PR TITLE
Adding "Getting Started" Documentation

### PR DESCRIPTION
**Pull request by mfixstsci**
Adding quick start documentation to MOSViz

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
@mfixstsci A couple of small things to add to this that might help some questions on the issue.

Somewhere we should add a reference on how to install it.  Currently the **dev** version can be installed in conda using:
```
$ conda install -c glueviz/label/dev mosviz
```

Then, second, I would show that mosviz can be started up right from the command line:
```
$ source activate mosviz-conda-environment
$ mosviz
```

And maybe even better with the dataset so it is auto-loaded...
```
$ source activate mosviz-conda-environment
$ mosviz deimos_mosviz.tbl
```

We might even want to backup one step of how to create a conda environment...

**Comment by mfixstsci** [comment]
@brechmos-stsci there is a doc on how to install MOSViz but I don't know if this information is in there. I do reference that once you have MOSViz installed (with a link to the docs) then enter `$ mosviz` etc.

**Comment by nluetzge** [comment]
Its much clearer now thank you! I think the installation doc also needs some updates there are some dependencies missing if you install it with pip or from source I think (such as regions).

**Comment by brechmos-stsci** [comment]
@nluetzge The regions dependency issue is being fixed in https://github.com/spacetelescope/mosviz/pull/140. So all dependencies should be automatically installed. 🤞  :)

**Comment by mfixstsci** [comment]
@nluetzge I spoke with @brechmos-stsci about this and he suggested that the pip install should be included in the wiki and that we should remove it from the install instructions.

**Comment by brechmos-stsci** [comment]
@mfixstsci @nluetzge I may not have been clear, what I had in my head is that pip install from github should be on a wiki or something. The conda install is the official way of doing it as conda is able to install all the dependencies including QT. This will be packaged on pypy but that might require a bit more work on the users part to make sure QT/pyqt is installed before doing pip install from pypy.  Sorry, I don't think that was clear when I was mentioning it.

I think, for now, conda will be the official install. We *are* going to package it up for pypy but it will probably take more work on the users part.  There are some possible packaging solutions to include qt/pyqt for pip but we have not investigated those yet.

**Comment by nluetzge** [comment]
Ok are we talking about the installation instructions here? https://mosviz-astrofrog.readthedocs.io/en/latest/installation.html Because one more thing I realized there is that it says it doesn't matter if its Python 2 or Python 3 but it won't install with Python 2 anymore (I also experimented with the source installation). I think this should also be clear for the conda installation. (maybe we should also include how to create the correct environment for this as @brechmos-stsci already mentioned.

**Comment by brechmos-stsci** [comment]
Ah, good point @nluetzge, we should state in there that we are supporting only Python 3.5 and above. @mfixstsci  could you add that in there?

**Comment by mfixstsci** [comment]
@brechmos-stsci okay, thanks for clarifying. Should we go ahead and remove the pip install section from the docs? @nluetzge The docs did state that it worked for python 2 but python 3 was the preferred version. I removed the section where it said that we support python 2 but didn't explicitly state that you should be using python 3. I can make sure to add it in there now.

**Comment by brechmos-stsci** [comment]
@mfixstsci I think the read the docs should be clear that conda is the installation method.  You could have a sub section saying that it is (well, will be) uploaded to pypy and therefore will be pip installable but it will be on the user to make sure their environment is setup to run QT/pyqt etc.  How is that?

**Comment by nluetzge** [comment]
@mfixstsci Sorry I didn't see that you already updated the installation docs. I'm still not sure where to look for the latest versions of those.

**Comment by nluetzge** [comment]
@brechmos-stsci Just tried to install the dev version through conda and its still complaining about the regions. Is this already in place? (I assume it only works once it is merged?)

**Comment by brechmos-stsci** [comment]
@nluetzge I'll have to check with @astrofrog. I thought he had it going but will check.

**Comment by brechmos-stsci** [comment]
@nluetzge Silly me. That PR is about to be merged in the next 30 mins. As soon as it is, I'll get @astrofrog to redo the dev build so that it should be active.

**Comment by mfixstsci** [comment]
@brechmos-stsci I think that is a good idea. I think that we should definitely mention that Conda is the preferred way but you can install via pip. We can just make sure that they are aware that they will have to install other packages if they choose this installation method. @nluetzge yeah, it is a little but more difficult to see because the sphinx docs don't get updated when I make commits. Here is the most recent version: 

https://github.com/spacetelescope/mosviz/blob/cc4c3f2c25799ac4b38d1304c940e0908f4a533e/docs/installation.rst

**Comment by mfixstsci** [comment]
@brechmos-stsci I just added a warning. If you would like something else added to the text let me know.

**Comment by nluetzge** [comment]
@brechmos-stsci I saw it is merged now. Is it already built in the dev version? Then I can try the installation again.

**Pull request merged**
