### PR TITLE
Show a GUI dialog to select the data factories and column names for the spectra and cutouts

### PR DESCRIPTION
**Pull request by astrofrog**
With this PR, when a dataset is added to a MOSViz viewer, a dialog pops up to confirm the column names and data factories to use:

screen shot 2017-05-18 at 16 52 21

Users can easily register new data factories using the usual glue infrastructure and adding a decorator to indicate that the loader is specifically useful for MOSViz, e.g.:

```python
@mosviz_cutout_loader('NIRCam Image')
def nircam_image_reader(file_name):
    """
    ...
```

This uses the existing method of checking the metadata to see if the user already set the default loaders or column names, and uses these as default.

The advantage of this dialog is that the table no longer **has** to be in ECSV, any table will do any and any column names will work so this is a lot more general.

@nmearl @mattjhill - do you like this approach?

Things to do if so:

* [x] Only show this once for a dataset and don't show it for subsets
* [x] Update documentation

### CODE REVIEW

**Comment by hcferguson** [comment]
Looks good to me.

**Comment by astrofrog** [comment]
Note that this now enables the documentation build in Travis which makes sure that all references work correctly.

**Comment by astrofrog** [comment]
@nmearl @mattjhill @hcferguson - this is ready for review and ready to merge if all good.

Note that at the moment the slit parameters are *not* used even though the GUI asks for them. Since this PR is getting pretty large, I'd prefer to merge as-is, and I'm planning on fixing the slit overlay functionality in a follow-up PR. For anyone who wants to see the rendered docs, you can find them here:

http://mosviz-astrofrog.readthedocs.io/en/latest/readingindata.html

**Comment by astrofrog** [comment]
Since @nmearl approved this, I'll go ahead and merge and open up follow-up pull requests

**Pull request merged**
