### PR TITLE
Reading in data Doc page

### PR DESCRIPTION
**Pull request by mattjhill**
I've written at least a draft of the tutorial on writing your own data loaders/reading in data.  It would probably be good to have some fresh eyes look it over before merging.

### CODE REVIEW

**Comment by justincely** [comment]
looks like this is failing becuase pytest is tying to execute the code-block in the .rst file as a test.  I think this can be disabled by changing `doctest_plus = disabled` in the setup.cfg file, though i think that would turn off all doc-testing in the future.  @pllim do you have experience with this?

**Comment by justincely** [comment]
@mattjhill for documentation changes - can you do a local build and stick it somewhere on central store for us to look at the rendered copy?

**Comment by mattjhill** [comment]
Build is fine for me locally. The output is in `/user/mhill/mosviz-docs/_build`.

**Comment by pllim** [comment]
Re: doctest. You can disable `doctest` just for that page by putting this incantation at the very top of the RST file without having to modify setup:

```
.. doctest-skip-all
```

**Comment by pllim** [comment]
Huh, that incantation did not work in your case. Not sure why. Works for me for `astropy.vo.client.conesearch` documentation. I wonder replacing:
```
... pass to MOSViz.

.. code-block:: python

    >>> blahblah
```
with
```
... pass to MOSViz::

    >>> blahblah
```
would change anything?

**Comment by mattjhill** [comment]
We'll find out

**Comment by pllim** [comment]
Nope. That is weird. I'll pull in your branch and try a few things.

**Comment by pllim** [comment]
I got doctest to pass locally with mattjhill/mosviz#4. Once that is merge, Travis for this PR should kick off again and we'll see.

**Comment by pllim** [comment]
I notice that despite passing locally, it still failed on my own fork's Travis build. The main difference is that my local test uses pytest 2.x bundled with Astropy but MOSViz uses pytest 3.x on Travis. I think the real fix here is to use pytest bundled with Astropy. I don't know why it is not doing that by default here.

**Comment by pllim** [comment]
I believe mattjhill/mosviz#5 will fix the problem by pinning pytest to 2.x for now.

**Comment by mattjhill** [comment]
Any progress on this? I would be really good to have the docs up for next week.  Is it vital to have doctest enabled?

**Comment by nmearl** [comment]
I'm not sure why we have it on by default. It makes more sense for us to explicitly mark a code block with `... doctest::` to trigger doc testing.

I think we should just set the `doctest_test_doctest_blocks` flag to `None` in the `config.py`, and have the user explicitly tell the system to test code blocks in the doc if they need to.

**Comment by pllim** [comment]
@mattjhill , just merge my second PR to your PR and the problem will be fixed.

**Comment by pllim** [comment]
Pass. Merging.

**Pull request merged**
