### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by kassin**
Do I need to do this for each change to the documentation?

### CODE REVIEW

**Comment by justincely** [comment]
you can group your changes together as a big documentation pull-request.  So you can do multiple commits, multiple updates, and issue the pull request when you've gotten everything how you want it.

**Comment by astrofrog** [comment]
@kassin - if you want to make more changes, you can go to the ``patch-1`` branch of your fork:

https://github.com/kassin/mosviz/tree/patch-1

and edit files there through the GitHub interface, and they will appear in this pull request anytime you make a change

**Comment by justincely** [comment]
you can also push new commits to the same branch on your fork, and the pull request will be automatically updated

**Comment by pllim** [comment]
Looks like this has been superseded by #33 , so closing this one.

**Pull request closed without merging**
