### PR TITLE
Add Deprecation Warning to Docs

### PR DESCRIPTION
**Pull request by duytnguyendtn**
Adds a Deprecation Warning to the top of all doc pages directing users to Jdaviz for maintained mosviz development

### CODE REVIEW

**Review by rosteen — CHANGES_REQUESTED** [review]
Need to do a find/replace Specviz -> Mosviz, looks like you only changed it in the first file.

**Comment by duytnguyendtn** [comment]
Oops, thanks for the catch! Fixed it

**Review by rosteen — APPROVED** [review]
Looks good, thanks.

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
