### PR TITLE
Builds "last working release" for Qt-based MosViz

### PR DESCRIPTION
**Pull request by ibusko**
This PR fixes the old Qt-based MosViz desktop app to the point it pops up the UI after a local installation from sources in a clean environment.

This doesn't mean the app works. A number of errors at CI testing suggests that some work is still needed in the code itself in order to get it to run correctly.

Should we care about CI errors for this "last release"?

### CODE REVIEW

**Review by rosteen — COMMENTED** [review]
Master has a requirement of `pyqt5<5.12`, but I don't see that line removed here (just the addition of the exact requirement). I had to resolve that when I pulled down your branch...maybe do a rebase to master to make sure it matches?

**Comment by ibusko** [comment]
@rosteen I removed the conflicting dependency. Should be good to go now.

**Review by rosteen — APPROVED** [review]
Installs successfully, and I can at least run it and get the UI.

**Review by eteq — APPROVED** [review]
As before I'm not too worried about the CI errors since it's probably the CI itself.

**Pull request merged**
