### PR TITLE
Add ability to ingest and display level-2 products

### PR DESCRIPTION
**Pull request by ibusko**
This PR adds the ability to optionally read and handle level-2 products. Presented with an existing MOSVIZ input table, the app should handle it as usual. When the table is augmented with an extra level-2 column with level-2 2D spectra file names, it will read these additional files and make them available for display.

The code works but in a few places can benefit from a bit of refactoring. This is mostly due to the nature of the sprint, in which multiple contributors add changes quickly and almost simultaneously. Some of these changes may benefit from some re-work in order to mesh better with one another.  I intend to work on that later, time allowing.

### CODE REVIEW

**Comment by hcferguson** [comment]
@ibusko If the level 2 products are delivered in separate files for the 2D and 1D products, it seems like you will need to have two level-2 columns in the table, rather than just one.

**Comment by ibusko** [comment]
Indeed. This is a first cut on the issue. Based on the data I have at hand. We will need yet another column for the 1D-extracted level-2 data. 

An associated problem is: is any part of these level-2 data optional? Or are we going to make all of it mandatory in MOSVIZ? I ask because the coding effort is significantly larger in case we want to leave things optional. There is a lot more conditionals in the code. Or, put another way, the state of the application becomes more complex as we make more things optional.

**Comment by hcferguson** [comment]
As far as MOSViz goes, we should consider it optional to have level 2 data at all, and should blank out the relevant window if either the 1D or 2D products are missing, but the other is there.

**Comment by nmearl** [comment]
Just a comment to keep an eye on docstring formatting. We should all be following the [numpy docstring standards](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard), and remembering to ensure that exposed functions have some kind of meaningful statement (looking at line 159's "THIS IS A TEST!" exclamation 😜 ).

**Pull request merged**
