### PR TITLE
Updates to packaging infrastructure

### LINKED ISSUE #154: Don't require numpy for setup?
Since MOSViz is pure Python, I don't think numpy is required for the setup, so we should remove ``setup_requires``:

https://github.com/spacetelescope/mosviz/blob/master/setup.py#L153

### LINKED ISSUE #163: Cleanup on setup file

### PR DESCRIPTION
**Pull request by drdavella**
This fixes #154 and fixes #163. It removes all use of `astropy_helpers`, which should make package maintenance significantly easier. It also significantly simplifies `setup.py` by moving all package configuration information and metadata to `setup.cfg`.

### CODE REVIEW

**Comment by drdavella** [comment]
@astrofrog yes I just need to change a few things in the test matrix that previously relied on `setup.py` commands from `astropy_helpers`.

**Comment by drdavella** [comment]
I'm pretty sure that this should work once #181 is merged and we rebase.

**Comment by brechmos-stsci** [comment]
I talked with @robelgeda and he is good for us to merge it.

This does remove the astropy_helpers requirement for this repo, so, after a rebase the `astropy_helpers` directory **might** linger on your local machine but can be safely deleted.

**Comment by brechmos-stsci** [comment]
For me, my `astropy_helpers` directory was auto-deleted as part of the reabase.

**Pull request merged**
